### ISSUE TITLE
ERROR: Burked bcrypt import error   

### ISSUE THREAD

**Issue by ManLikeGhost** [fashlogue/fashlogue-api#13]
ERROR:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ekpo eddy\AppData\Roaming\npm-cache_logs\2019-01-22T11_22_15_061Z-debug.log

in the package.JSONfile the dependency was name "bcrypt-nodejs" but imported as "bcrypt"

1. npm install --save bcrypt-nodejs && npm uninstall --save bcrypt
2. Run "npm run dev"

**How to solve**
1. Go to package.json file
2.  Copy the dependency:" bcrypt-nodejs"
3. Open the root file of the app => src => app => user.model.ts
4. Change the import statement on line  to "import * as bcrypt from 'bcrypt-nodejs';
5. Open bash run "npm run dev"

**Expected behavior**
1:22:39 PM - Starting compilation in watch mode...                                                                                                                                                                                                 1:22:45 PM - Found 0 errors. Watching for file changes.                                                                                                           > fashlogue-api@1.0.0 serve C:\Users\ekpo eddy\Documents\Nodejs\fashlogue-api    > SET NODE_ENV=development && node dist/server.js                                                                                                                 (node:17148) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, u se `openUri()` instead, or set the `useMongoClient` option if using `connect()`  or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.htm l#use-mongo-client                                                               connected to development database
--

PS:Remember to check for a ".env file"

**Comment by ogbiyoyosky** [comment]
Since it’s solve please make a PR
